### ISSUE TITLE
[Question] Goodbye REST in favor of what?

### ISSUE THREAD

**Issue by BenEmdon** [jaydenwindle/django-graphql-talk#1]
Hey @jaydenwindle 👋 

Long time no see! 
The slides for this talk aren't up yet and I'm just curious what this talk is about 👀

**Comment by jaydenwindle** [comment]
Hey Ben!

Yeah, it's been way too long! Let's catch up some time when I'm back in Ottawa.

The talk was about Django + GraphQL. I went through how we switched from REST to GraphQL to build Jetpack's v3 API, did a mini-tutorial on building GraphQL APIs with Django, then talked a bit about the tradeoffs and our experience running it in production. 

I've uploaded the slides + demo code and updated the readme with a bit more info about the talk.

**Comment by BenEmdon** [comment]
Awesome! Can't wait to check it out!
